# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: "windows-latest"

stages:
  - stage: Compile
    jobs:
      - job: Build
        steps:
          - powershell: .\build.ps1 -target Build

  - stage: Test
    jobs:
      - job: UnitTest
        steps:
          - powershell: .\build.ps1 -target UnitTest

      - job: Coverage
        steps:
          - powershell: .\build.ps1 -target Coverage

  - stage: Deploy
    jobs:
      - job: Publish
        steps:
          - powershell: .\build.ps1 -target Publish -configuration Release
